import Foundation
import SwiftUI

// Per-session metadata pulled from the JSONL. Title precedence:
//   custom-title (set via /rename)
//   ai-title     (auto-generated by Claude)
//   agent-name   (rare; usually mirrors custom-title)
//   firstPrompt  (first real user message — best heuristic when nothing
//                 else is set; especially valuable for home-dir sessions
//                 that would otherwise collapse to a bare "~")
// Color comes from the latest agent-color record in the file.
// Cached by (url, mtime) so we don't re-read on every 3s rescan tick.
struct SessionMeta: Equatable {
    let title: String?
    let firstPrompt: String?
    let agentColor: String?
}

extension SessionMeta {
    var swiftUIColor: Color? {
        guard let raw = agentColor?.lowercased(), !raw.isEmpty else { return nil }
        switch raw {
        case "red":           return .red
        case "orange":        return .orange
        case "yellow":        return .yellow
        case "green":         return .green
        case "mint":          return .mint
        case "teal":          return .teal
        case "cyan":          return .cyan
        case "blue":          return .blue
        case "indigo":        return .indigo
        case "purple":        return .purple
        case "pink":          return .pink
        case "brown":         return .brown
        case "gray", "grey":  return .gray
        default:              return nil
        }
    }
}

enum SessionTitle {
    private struct CacheEntry {
        let mtime: Date
        let meta: SessionMeta
    }

    private static var cache: [URL: CacheEntry] = [:]
    private static let cacheLock = NSLock()

    static func resolve(url: URL, mtime: Date) -> String? {
        meta(url: url, mtime: mtime).title
    }

    static func meta(url: URL, mtime: Date) -> SessionMeta {
        cacheLock.lock()
        if let entry = cache[url], entry.mtime == mtime {
            cacheLock.unlock()
            return entry.meta
        }
        cacheLock.unlock()

        let parsed = parseMeta(url: url)
        cacheLock.lock()
        cache[url] = CacheEntry(mtime: mtime, meta: parsed)
        cacheLock.unlock()
        return parsed
    }

    // MARK: - Lightweight scanning structs

    // Lean Decodable specifically for the metadata scan — pulls out just the
    // fields we care about so the JSONDecoder doesn't have to walk the full
    // SessionRecord shape for each line.
    private struct MetaRecord: Decodable {
        let type: String
        let customTitle: String?
        let aiTitle: String?
        let agentName: String?
        let agentColor: String?
        let isMeta: Bool?
        let message: MessageBox?
    }

    private struct MessageBox: Decodable {
        let role: String?
        let content: ContentField?
    }

    // User content is usually a plain string (the typed prompt). Tool-result
    // follow-ups are arrays of parts; we ignore those — they're never the
    // session's leading prompt.
    private enum ContentField: Decodable {
        case text(String)
        case parts
        init(from decoder: Decoder) throws {
            let c = try decoder.singleValueContainer()
            if let s = try? c.decode(String.self) { self = .text(s); return }
            self = .parts
        }
        var asString: String? {
            if case .text(let s) = self { return s } else { return nil }
        }
    }

    private static func parseMeta(url: URL) -> SessionMeta {
        guard let data = try? Data(contentsOf: url) else {
            return SessionMeta(title: nil, firstPrompt: nil, agentColor: nil)
        }
        let decoder = JSONDecoder()

        var customTitle: String?
        var aiTitle: String?
        var agentName: String?
        var agentColor: String?
        var firstPrompt: String?

        let newline = UInt8(ascii: "\n")
        var start = data.startIndex
        for i in data.indices {
            if data[i] == newline {
                if start < i {
                    let line = data[start..<i]
                    if let rec = try? decoder.decode(MetaRecord.self, from: line) {
                        switch rec.type {
                        case "custom-title":
                            if let t = rec.customTitle, !t.isEmpty { customTitle = t }
                        case "ai-title":
                            if let t = rec.aiTitle, !t.isEmpty { aiTitle = t }
                        case "agent-name":
                            if let t = rec.agentName, !t.isEmpty { agentName = t }
                        case "agent-color":
                            if let c = rec.agentColor, !c.isEmpty { agentColor = c }
                        case "user":
                            // First real user prompt (skip meta records like
                            // command caveats and skill triggers).
                            if firstPrompt == nil,
                               rec.isMeta != true,
                               let s = rec.message?.content?.asString,
                               looksLikeRealPrompt(s)
                            {
                                firstPrompt = trim(s)
                            }
                        default:
                            break
                        }
                    }
                }
                start = data.index(after: i)
            }
        }
        return SessionMeta(
            title: customTitle ?? aiTitle ?? agentName,
            firstPrompt: firstPrompt,
            agentColor: agentColor
        )
    }

    // Filter out the system-injected user records that aren't actual prompts —
    // command captures, system reminders, slash-command output, etc.
    private static func looksLikeRealPrompt(_ s: String) -> Bool {
        let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed.isEmpty { return false }
        // These wrappers are injected by Claude Code, not typed by the user.
        let skipPrefixes = [
            "<local-command-caveat>",
            "<command-name>",
            "<system-reminder>",
            "<command-message>",
            "<command-args>",
            "Caveat: The messages",
        ]
        for p in skipPrefixes where trimmed.hasPrefix(p) { return false }
        return true
    }

    private static func trim(_ s: String) -> String {
        let single = s
            .replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\t", with: " ")
            .trimmingCharacters(in: .whitespaces)
        if single.count <= 60 { return single }
        return String(single.prefix(60)) + "…"
    }
}
