import Foundation
import SwiftUI

// Per-session metadata pulled from the JSONL. Title precedence:
//   custom-title (set via /rename)
//   ai-title     (auto-generated by Claude)
//   agent-name   (rare; usually mirrors custom-title)
//   firstPrompt  (first real user message — best heuristic when nothing
//                 else is set; especially valuable for home-dir sessions
//                 that would otherwise collapse to a bare "~")
// Color comes from the latest agent-color record in the file.
// Cached by (url, mtime) so we don't re-read on every 3s rescan tick.
struct SessionMeta: Equatable {
    let title: String?
    let firstPrompt: String?
    let agentColor: String?
    let cwd: String?         // working directory the session was started in
    let awaySummary: String? // Claude's auto-generated "where we are" summary
}

extension SessionMeta {
    var swiftUIColor: Color? {
        guard let raw = agentColor?.lowercased(), !raw.isEmpty else { return nil }
        switch raw {
        case "red":           return .red
        case "orange":        return .orange
        case "yellow":        return .yellow
        case "green":         return .green
        case "mint":          return .mint
        case "teal":          return .teal
        case "cyan":          return .cyan
        case "blue":          return .blue
        case "indigo":        return .indigo
        case "purple":        return .purple
        case "pink":          return .pink
        case "brown":         return .brown
        case "gray", "grey":  return .gray
        default:              return nil
        }
    }
}

enum SessionTitle {
    private struct CacheEntry {
        let mtime: Date
        let meta: SessionMeta
    }

    private static var cache: [URL: CacheEntry] = [:]
    private static let cacheLock = NSLock()

    static func resolve(url: URL, mtime: Date) -> String? {
        meta(url: url, mtime: mtime).title
    }

    static func meta(url: URL, mtime: Date) -> SessionMeta {
        cacheLock.lock()
        if let entry = cache[url], entry.mtime == mtime {
            cacheLock.unlock()
            return entry.meta
        }
        cacheLock.unlock()

        let parsed = parseMeta(url: url)
        cacheLock.lock()
        cache[url] = CacheEntry(mtime: mtime, meta: parsed)
        cacheLock.unlock()
        return parsed
    }

    // MARK: - Lightweight scanning structs

    // Lean Decodable specifically for the metadata scan — pulls out just the
    // fields we care about so the JSONDecoder doesn't have to walk the full
    // SessionRecord shape for each line.
    private struct MetaRecord: Decodable {
        let type: String
        let subtype: String?
        let customTitle: String?
        let aiTitle: String?
        let agentName: String?
        let agentColor: String?
        let cwd: String?
        let content: String?     // away_summary.content lives here
        let isMeta: Bool?
        let message: MessageBox?
    }

    private struct MessageBox: Decodable {
        let role: String?
        let content: ContentField?
    }

    // User content is usually a plain string (the typed prompt). Tool-result
    // follow-ups are arrays of parts; we ignore those — they're never the
    // session's leading prompt.
    private enum ContentField: Decodable {
        case text(String)
        case parts
        init(from decoder: Decoder) throws {
            let c = try decoder.singleValueContainer()
            if let s = try? c.decode(String.self) { self = .text(s); return }
            self = .parts
        }
        var asString: String? {
            if case .text(let s) = self { return s } else { return nil }
        }
    }

    private static func parseMeta(url: URL) -> SessionMeta {
        guard let data = try? Data(contentsOf: url) else {
            return SessionMeta(title: nil, firstPrompt: nil, agentColor: nil, cwd: nil, awaySummary: nil)
        }
        let decoder = JSONDecoder()

        var customTitle: String?
        var aiTitle: String?
        var agentName: String?
        var agentColor: String?
        var firstPrompt: String?
        var cwd: String?
        var awaySummary: String?

        let newline = UInt8(ascii: "\n")
        var start = data.startIndex
        for i in data.indices {
            if data[i] == newline {
                if start < i {
                    let line = data[start..<i]
                    if let rec = try? decoder.decode(MetaRecord.self, from: line) {
                        // cwd lives on user / assistant / system records; take
                        // the first one we find — it's stable for the session.
                        if cwd == nil, let c = rec.cwd, !c.isEmpty { cwd = c }
                        switch rec.type {
                        case "custom-title":
                            if let t = rec.customTitle, !t.isEmpty { customTitle = t }
                        case "ai-title":
                            if let t = rec.aiTitle, !t.isEmpty { aiTitle = t }
                        case "agent-name":
                            if let t = rec.agentName, !t.isEmpty { agentName = t }
                        case "agent-color":
                            if let c = rec.agentColor, !c.isEmpty { agentColor = c }
                        case "user":
                            if firstPrompt == nil,
                               rec.isMeta != true,
                               let s = rec.message?.content?.asString,
                               let real = extractRealPromptText(s)
                            {
                                firstPrompt = trim(real)
                            }
                        case "system":
                            // Most recent away_summary wins — Claude writes
                            // a fresh one as the session progresses.
                            if rec.subtype == "away_summary",
                               let c = rec.content, !c.isEmpty
                            {
                                awaySummary = c
                            }
                        default:
                            break
                        }
                    }
                }
                start = data.index(after: i)
            }
        }
        return SessionMeta(
            title: customTitle ?? aiTitle ?? agentName,
            firstPrompt: firstPrompt,
            agentColor: agentColor,
            cwd: cwd,
            awaySummary: awaySummary
        )
    }

    // Strip the system-injected XML-style wrappers that Claude Code emits
    // around slash commands (<command-name>, <local-command-stdout>,
    // <system-reminder>, etc.) and return whatever the user actually typed.
    // Returns nil if the entire content is wrappers.
    private static func extractRealPromptText(_ content: String) -> String? {
        // Iteratively remove paired <tag>...</tag> blocks. The non-greedy
        // `[\s\S]*?` plus `</\1>` backreference matches against the opening
        // tag name. Loop in case nested or consecutive tag blocks remain
        // after a single pass.
        let pattern = "<([a-zA-Z][a-zA-Z0-9-]*)[^>]*>[\\s\\S]*?</\\1>"
        var stripped = content
        var previous = ""
        while previous != stripped {
            previous = stripped
            stripped = stripped.replacingOccurrences(
                of: pattern,
                with: "",
                options: .regularExpression
            )
        }
        // Also strip leading "Caveat:" sentences that some older sessions
        // contain without an enclosing tag.
        stripped = stripped.replacingOccurrences(
            of: "^Caveat: [^\\n]+\\n+",
            with: "",
            options: [.regularExpression, .anchored]
        )
        stripped = stripped.trimmingCharacters(in: .whitespacesAndNewlines)
        return stripped.isEmpty ? nil : stripped
    }

    private static func trim(_ s: String) -> String {
        let single = s
            .replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\t", with: " ")
            .trimmingCharacters(in: .whitespaces)
        if single.count <= 60 { return single }
        return String(single.prefix(60)) + "…"
    }
}
