import Foundation
import SwiftUI

// Per-session metadata pulled from the JSONL. Title precedence:
//   custom-title (set via /rename)
//   ai-title     (auto-generated by Claude)
//   agent-name   (rare; usually mirrors custom-title)
// Color comes from the latest agent-color record in the file.
// Cached by (url, mtime) so we don't re-read on every 3s rescan tick.
struct SessionMeta: Equatable {
    let title: String?
    let agentColor: String?
}

extension SessionMeta {
    var swiftUIColor: Color? {
        guard let raw = agentColor?.lowercased(), !raw.isEmpty else { return nil }
        switch raw {
        case "red":           return .red
        case "orange":        return .orange
        case "yellow":        return .yellow
        case "green":         return .green
        case "mint":          return .mint
        case "teal":          return .teal
        case "cyan":          return .cyan
        case "blue":          return .blue
        case "indigo":        return .indigo
        case "purple":        return .purple
        case "pink":          return .pink
        case "brown":         return .brown
        case "gray", "grey":  return .gray
        default:              return nil
        }
    }
}

enum SessionTitle {
    private struct CacheEntry {
        let mtime: Date
        let meta: SessionMeta
    }

    private static var cache: [URL: CacheEntry] = [:]
    private static let cacheLock = NSLock()

    static func resolve(url: URL, mtime: Date) -> String? {
        meta(url: url, mtime: mtime).title
    }

    static func meta(url: URL, mtime: Date) -> SessionMeta {
        cacheLock.lock()
        if let entry = cache[url], entry.mtime == mtime {
            cacheLock.unlock()
            return entry.meta
        }
        cacheLock.unlock()

        let parsed = parseMeta(url: url)
        cacheLock.lock()
        cache[url] = CacheEntry(mtime: mtime, meta: parsed)
        cacheLock.unlock()
        return parsed
    }

    private struct MetaRecord: Decodable {
        let type: String
        let customTitle: String?
        let aiTitle: String?
        let agentName: String?
        let agentColor: String?
    }

    private static func parseMeta(url: URL) -> SessionMeta {
        guard let data = try? Data(contentsOf: url) else {
            return SessionMeta(title: nil, agentColor: nil)
        }
        let decoder = JSONDecoder()

        var customTitle: String?
        var aiTitle: String?
        var agentName: String?
        var agentColor: String?

        let newline = UInt8(ascii: "\n")
        var start = data.startIndex
        for i in data.indices {
            if data[i] == newline {
                if start < i {
                    let line = data[start..<i]
                    if let rec = try? decoder.decode(MetaRecord.self, from: line) {
                        switch rec.type {
                        case "custom-title":
                            if let t = rec.customTitle, !t.isEmpty { customTitle = t }
                        case "ai-title":
                            if let t = rec.aiTitle, !t.isEmpty { aiTitle = t }
                        case "agent-name":
                            if let t = rec.agentName, !t.isEmpty { agentName = t }
                        case "agent-color":
                            if let c = rec.agentColor, !c.isEmpty { agentColor = c }
                        default:
                            break
                        }
                    }
                }
                start = data.index(after: i)
            }
        }
        return SessionMeta(
            title: customTitle ?? aiTitle ?? agentName,
            agentColor: agentColor
        )
    }
}
